In [1]:
# visualization
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
fe = fm.FontEntry(
    fname=r'/usr/share/fonts/truetype/nanum/NanumGothic.ttf', # ttf 파일이 저장되어 있는 경로
    name='NanumBarunGothic')                        # 이 폰트의 원하는 이름 설정
fm.fontManager.ttflist.insert(0, fe)              # Matplotlib에 폰트 추가
plt.rcParams.update({'font.size': 10, 'font.family': 'NanumBarunGothic'}) # 폰트 설정
plt.rc('font', family='NanumBarunGothic')
import seaborn as sns

# utils
import pandas as pd
import numpy as np
from tqdm import tqdm
import pickle
import warnings;warnings.filterwarnings('ignore')

In [2]:
train_path = "../modified_data/v01_train.csv"
test_path = "../modified_data/v01_teest.csv"

In [3]:
train = pd.read_csv(train_path, index_col=0)
test = pd.read_csv(test_path,index_col=0)

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
train.head(10)

,시군구,번지,본번,부번,아파트명,전용면적(㎡),계약년월,계약일,층,건축년도,해제사유발생일,등기신청일자,거래유형,중개사소재지,"k-단지분류(아파트,주상복합등등)",k-세대타입(분양형태),k-복도유형,k-난방방식,k-전체동수,k-전체세대수,k-건설사(시공사),k-사용검사일-사용승인일,k-연면적,k-주거전용면적,k-관리비부과면적,k-전용면적별세대현황(60㎡이하),k-전용면적별세대현황(60㎡~85㎡이하),k-85㎡~135㎡이하,k-135㎡초과,k-등록일자,k-수정일자,건축면적,주차대수,기타/의무/임대/임의=1/2/3/4,단지승인일,사용허가여부,관리비 업로드,좌표X,좌표Y,단지신청일,target
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201712,8,3,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,124000.0
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201712,22,4,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,123500.0
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,54.98,201712,28,5,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,91500.0
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,3,4,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,130000.0
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,8,2,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,117000.0
5,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,11,1,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,130000.0
6,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201803,19,2,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,139500.0
7,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,54.98,201804,5,5,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,107500.0
8,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201806,28,3,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,145000.0
9,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,54.98,201807,9,3,1987,NaN,,-,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,112000.0

In [6]:
train[~train["해제사유발생일"].isnull()].head(10)

,시군구,번지,본번,부번,아파트명,전용면적(㎡),계약년월,계약일,층,건축년도,해제사유발생일,등기신청일자,거래유형,중개사소재지,"k-단지분류(아파트,주상복합등등)",k-세대타입(분양형태),k-복도유형,k-난방방식,k-전체동수,k-전체세대수,k-건설사(시공사),k-사용검사일-사용승인일,k-연면적,k-주거전용면적,k-관리비부과면적,k-전용면적별세대현황(60㎡이하),k-전용면적별세대현황(60㎡~85㎡이하),k-85㎡~135㎡이하,k-135㎡초과,k-등록일자,k-수정일자,건축면적,주차대수,기타/의무/임대/임의=1/2/3/4,단지승인일,사용허가여부,관리비 업로드,좌표X,좌표Y,단지신청일,target
201044,서울특별시 강남구 개포동,1280,1280.0,0.0,래미안블레스티지,59.9670,202304,18,22,2019,20230515.0,,중개거래,서울 강남구,아파트,기타,계단식,지역난방,23.0,1957.0,삼성물산,2019-02-26 00:00:00.0,362895.0,160922.0,215907.0,661.0,780.0,511.0,NaN,2019-03-09 05:56:52.0,2023-09-23 17:20:52.0,16155.05,3153.0,의무,2019-03-14 11:33:30.0,Y,N,127.064151,37.480049,2019-03-09 05:56:52.0,185000.0
201047,서울특별시 강남구 개포동,1280,1280.0,0.0,래미안블레스티지,84.9400,202304,26,26,2019,20230614.0,,중개거래,서울 강남구,아파트,기타,계단식,지역난방,23.0,1957.0,삼성물산,2019-02-26 00:00:00.0,362895.0,160922.0,215907.0,661.0,780.0,511.0,NaN,2019-03-09 05:56:52.0,2023-09-23 17:20:52.0,16155.05,3153.0,의무,2019-03-14 11:33:30.0,Y,N,127.064151,37.480049,2019-03-09 05:56:52.0,249500.0
201050,서울특별시 강남구 개포동,1280,1280.0,0.0,래미안블레스티지,59.9670,202305,8,16,2019,20230712.0,,중개거래,서울 강남구,아파트,기타,계단식,지역난방,23.0,1957.0,삼성물산,2019-02-26 00:00:00.0,362895.0,160922.0,215907.0,661.0,780.0,511.0,NaN,2019-03-09 05:56:52.0,2023-09-23 17:20:52.0,16155.05,3153.0,의무,2019-03-14 11:33:30.0,Y,N,127.064151,37.480049,2019-03-09 05:56:52.0,190000.0
201079,서울특별시 강남구 대치동,1014-3,1014.0,3.0,대치삼성,84.5800,202306,2,8,2000,20230920.0,,중개거래,서울 강남구,아파트,분양,혼합식,지역난방,14.0,960.0,삼성물산,2000-07-31 00:00:00.0,142507.0,83135.0,83159.0,249.0,192.0,519.0,NaN,NaN,2023-09-23 17:45:56.0,8414.21,1238.0,의무,2013-06-23 14:22:18.0,Y,N,127.058356,37.496336,2013-03-07 09:46:34.0,220000.0
201083,서울특별시 강남구 대치동,1014-3,1014.0,3.0,대치삼성,97.3500,202306,3,4,2000,20230816.0,,중개거래,서울 강남구,아파트,분양,혼합식,지역난방,14.0,960.0,삼성물산,2000-07-31 00:00:00.0,142507.0,83135.0,83159.0,249.0,192.0,519.0,NaN,NaN,2023-09-23 17:45:56.0,8414.21,1238.0,의무,2013-06-23 14:22:18.0,Y,N,127.058356,37.496336,2013-03-07 09:46:34.0,240000.0
201089,서울특별시 강남구 대치동,1014-3,1014.0,3.0,대치삼성,59.8800,202306,29,2,2000,20230911.0,,중개거래,서울 강남구,아파트,분양,혼합식,지역난방,14.0,960.0,삼성물산,2000-07-31 00:00:00.0,142507.0,83135.0,83159.0,249.0,192.0,519.0,NaN,NaN,2023-09-23 17:45:56.0,8414.21,1238.0,의무,2013-06-23 14:22:18.0,Y,N,127.058356,37.496336,2013-03-07 09:46:34.0,162500.0
201160,서울특별시 강남구 도곡동,527,527.0,0.0,도곡렉슬,59.9937,202305,27,18,2006,20230727.0,,중개거래,서울 강남구,아파트,분양,계단식,지역난방,34.0,3002.0,"현대,쌍용,GS",2006-01-27 00:00:00.0,553661.0,298679.0,379722.0,601.0,936.0,1402.0,NaN,NaN,2023-09-20 21:31:32.0,20457.82,4443.0,의무,2013-06-23 14:21:13.0,Y,N,127.048985,37.493029,2013-03-07 09:46:20.0,179000.0
201172,서울특별시 강남구 도곡동,934-10,934.0,10.0,도곡우성,84.8300,202306,29,11,1986,20230721.0,,중개거래,서울 강남구,아파트,분양,혼합식,지역난방,2.0,390.0,우성건설,1986-10-31 00:00:00.0,40311.0,32577.0,39792.0,0.0,390.0,0.0,NaN,NaN,2023-09-20 21:36:10.0,0.00,330.0,의무,2013-06-17 13:35:11.0,Y,N,127.037124,37.488203,2013-03-07 09:46:46.0,175000.0
201195,서울특별시 강남구 개포동,1282,1282.0,0.0,개포래미안포레스트,84.8300,202303,30,27,2020,20230612.0,,중개거래,서울 강남구,아파트,기타,혼합식,지역난방,31.0,2296.0,삼성물산(주),2020-09-28 00:00:00.0,422390.0,178215.0,244894.0,900.0,905.0,458.0,NaN,2020-11-18 18:48:17.0,2023-09-23 17:21:46.0,20774.78,3961.0,의무,2021-01-13 10:20:10.0,Y,N,127.054031,37.478480,2021-01-12 13:52:06.0,232000.0
201200,서울특별시 강남구 개포동,1282,1282.0,0.0,개포래미안포레스트,74.6600,202304,24,6,2020,20230515.0,,중개거래,서울 강남구,아파트,기타,혼합식,지역난방,31.0,2296.0,삼성물산(주),2020-09-28 00:00:00.0,422390.0,178215.0,244894.0,900.0,905.0,458.0,NaN,2020-11-18 18:48:17.0,2023-09-23 17:21:46.0,20774.78,3961.0,의무,2021-01-13 10:20:10.0,Y,N,127.054031,37.478480,2021-01-12 13:52:06.0,212000.0

In [7]:
train[train["아파트명"]=="래미안블레스티지"][["아파트명","계약년월","계약일","해제사유발생일","등기신청일자","target"]]

            아파트명    계약년월  계약일     해제사유발생일    등기신청일자    target
201023  래미안블레스티지  202210    8         NaN            185000.0
201024  래미안블레스티지  202212    5         NaN            241000.0
201025  래미안블레스티지  202301    2         NaN  20230112  129000.0
201026  래미안블레스티지  202301   12         NaN  20230306  167400.0
201027  래미안블레스티지  202301   14         NaN  20230330  171000.0
201028  래미안블레스티지  202301   18         NaN  20230410  177000.0
201029  래미안블레스티지  202301   28         NaN  20230421  174000.0
201030  래미안블레스티지  202302    4         NaN  20230412  242000.0
201031  래미안블레스티지  202302    4         NaN  20230516  250000.0
201032  래미안블레스티지  202302   11         NaN  20230330  173000.0
201033  래미안블레스티지  202302   13         NaN  20230525  252000.0
201034  래미안블레스티지  202302   15         NaN  20230414  147000.0
201035  래미안블레스티지  202302   16         NaN  20230530  315000.0
201036  래미안블레스티지  202302   18         NaN  20230531  240000.0
201037  래미안블레스티지  202302   19         NaN  20230414  179000.0
201038  래미안블레스티지  202302   27         NaN  20230612  247000.0
201039  래미안블레스티지  202303    1         NaN  20230620  170000.0
201040  래미안블레스티지  202303    4         NaN  20230526  180000.0
201041  래미안블레스티지  202303   11         NaN  20230710  183000.0
201042  래미안블레스티지  202303   11         NaN  20230731  170000.0
201043  래미안블레스티지  202303   17         NaN  20230428  174000.0
201044  래미안블레스티지  202304   18  20230515.0            185000.0
201045  래미안블레스티지  202304   18         NaN  20230526  185000.0
201046  래미안블레스티지  202304   25         NaN  20230814  249500.0
201047  래미안블레스티지  202304   26  20230614.0            249500.0
201048  래미안블레스티지  202304   27         NaN  20230628  190000.0
201049  래미안블레스티지  202305    5         NaN  20230726  269500.0
201050  래미안블레스티지  202305    8  20230712.0            190000.0
201051  래미안블레스티지  202305    8         NaN  20230717  190000.0
201052  래미안블레스티지  202305   10         NaN  20230728  247000.0
201053  래미안블레스티지  202305   19         NaN  20230828  304500.0
201054  래미안블레스티지  202305   25         NaN  20230825  258000.0
201055  래미안블레스티지  202305   27         NaN            257000.0
201056  래미안블레스티지  202306    1         NaN  20230802  195500.0
201057  래미안블레스티지  202306    8         NaN            190000.0
201058  래미안블레스티지  202306   12         NaN  20230831  270000.0
201059  래미안블레스티지  202306   13         NaN  20230921  265000.0
201060  래미안블레스티지  202306   13         NaN  20230818  270000.0
201061  래미안블레스티지  202306   14         NaN            270000.0
201062  래미안블레스티지  202306   17         NaN  20230906  187000.0
201063  래미안블레스티지  202306   18         NaN  20230904  160000.0
201064  래미안블레스티지  202306   26         NaN            326500.0
222664  래미안블레스티지  202110    9         NaN            320000.0
222665  래미안블레스티지  202111   11         NaN            230000.0
222666  래미안블레스티지  202112   31         NaN            316000.0
222667  래미안블레스티지  202201   15         NaN            300000.0
222668  래미안블레스티지  202204   16         NaN            200000.0
222669  래미안블레스티지  202205   27         NaN            228500.0
222670  래미안블레스티지  202206   10         NaN            360000.0
222671  래미안블레스티지  202206   28         NaN            214000.0
222672  래미안블레스티지  202207   11         NaN            210000.0
222673  래미안블레스티지  202207   11         NaN            373000.0
238242  래미안블레스티지  202010   24         NaN            296500.0
238243  래미안블레스티지  202010   25         NaN            299000.0
238244  래미안블레스티지  202010   27         NaN            195000.0
238245  래미안블레스티지  202010   27         NaN            270000.0
238246  래미안블레스티지  202010   31         NaN            184000.0
238247  래미안블레스티지  202012    4         NaN            300000.0
238248  래미안블레스티지  202012    7         NaN            210000.0
238249  래미안블레스티지  202012   16         NaN            265000.0
238250  래미안블레스티지  202012   27         NaN            210000.0
238251  래미안블레스티지  202101    7         NaN            200000.0
238252  래미안블레스티지  202101   14         NaN            267000.0
238253  래미안블레스티지  202101   18  20210309.0            277000.0
238254  래미안블레스티지  202102    6         NaN            173000.0
238255  래미안블레스티지  202102   15         NaN            251000.0
238256  래미안블레스티지  202102   16         NaN            210000.0
238257  래미안블레스티지  202102   22         NaN            195000.0
238258  래미안블레스티지  202103    9         NaN            277000.0
238259  래미안블레스티지  202103   10         NaN            199000.0
238260  래미안블레스티지  202104    1         NaN            214500.0
238261  래미안블레스티지  202104   13         NaN            204500.0
238262  래미안블레스티지  202104   14         NaN            268000.0
238263  래미안블레스티지  202105    8         NaN            207500.0
238264  래미안블레스티지  202105    8         NaN            275000.0
238265  래미안블레스티지  202105   18         NaN            280000.0
238266  래미안블레스티지  202105   30         NaN            360000.0
238267  래미안블레스티지  202106    9         NaN            285000.0
238268  래미안블레스티지  202107   23         NaN            436000.0
238269  래미안블레스티지  202107   24         NaN            282000.0
238270  래미안블레스티지  202108    7         NaN            289000.0
238271  래미안블레스티지  202108   14         NaN            227000.0
238272  래미안블레스티지  202108   16         NaN            224500.0
238273  래미안블레스티지  202108   19  20210913.0            219000.0
238274  래미안블레스티지  202108   19         NaN            219000.0
238275  래미안블레스티지  202108   21         NaN            225000.0
238276  래미안블레스티지  202108   31         NaN            298000.0
238277  래미안블레스티지  202108   31         NaN            230000.0
238278  래미안블레스티지  202109    5         NaN            293000.0
238279  래미안블레스티지  202109    5         NaN            179000.0
238280  래미안블레스티지  202109   17         NaN            295000.0
293161  래미안블레스티지  201910    7         NaN            235000.0
293162  래미안블레스티지  201910    8         NaN            285000.0
293163  래미안블레스티지  201910   10         NaN            240000.0
293164  래미안블레스티지  201910   11         NaN            307000.0
293165  래미안블레스티지  201910   11         NaN            148000.0
293166  래미안블레스티지  201910   13         NaN            190000.0
293167  래미안블레스티지  201910   18         NaN            270000.0
293168  래미안블레스티지  201910   19         NaN            237000.0
293169  래미안블레스티지  201910   21         NaN            237000.0
293170  래미안블레스티지  201910   23         NaN            291000.0
293171  래미안블레스티지  201910   24         NaN            252000.0
293172  래미안블레스티지  201910   26         NaN            259000.0
293173  래미안블레스티지  201910   28         NaN            244000.0
293174  래미안블레스티지  201911    1         NaN            146000.0
293175  래미안블레스티지  201911   20         NaN            243000.0
293176  래미안블레스티지  201911   20         NaN            190000.0
293177  래미안블레스티지  201911   20         NaN            195000.0
293178  래미안블레스티지  201911   25         NaN            189000.0
293179  래미안블레스티지  201911   27         NaN            145000.0
293180  래미안블레스티지  201911   30         NaN            300000.0
293181  래미안블레스티지  201912    5         NaN            190000.0
293182  래미안블레스티지  201912    7         NaN            198000.0
293183  래미안블레스티지  201912   16         NaN            200000.0
293184  래미안블레스티지  201912   19         NaN            245000.0
293185  래미안블레스티지  201912   22         NaN            262000.0
293186  래미안블레스티지  201912   23         NaN            270000.0
293187  래미안블레스티지  201912   23         NaN            335000.0
293188  래미안블레스티지  201912   28         NaN            249000.0
293189  래미안블레스티지  202001   17         NaN            188000.0
293190  래미안블레스티지  202002   12         NaN            175000.0
293191  래미안블레스티지  202002   13         NaN            244000.0
293192  래미안블레스티지  202002   21         NaN            243000.0
293193  래미안블레스티지  202003   11         NaN            263000.0
293194  래미안블레스티지  202004   14         NaN            180000.0
293195  래미안블레스티지  202004   22         NaN            185000.0
293196  래미안블레스티지  202005    4         NaN            251000.0
293197  래미안블레스티지  202005    4         NaN            230000.0
293198  래미안블레스티지  202005   13         NaN            300000.0
293199  래미안블레스티지  202005   19         NaN            230000.0
293200  래미안블레스티지  202006    4         NaN            243000.0
293201  래미안블레스티지  202006    7         NaN            251000.0
293202  래미안블레스티지  202006    8         NaN            189000.0
293203  래미안블레스티지  202006   17         NaN            260000.0
293204  래미안블레스티지  202006   23         NaN            155000.0
293205  래미안블레스티지  202006   23  20200914.0            155000.0
293206  래미안블레스티지  202006   26         NaN            280000.0
293207  래미안블레스티지  202006   29         NaN            270000.0
293208  래미안블레스티지  202006   29         NaN            310000.0
293209  래미안블레스티지  202007    2         NaN            290000.0
293210  래미안블레스티지  202007    6         NaN            196000.0
293211  래미안블레스티지  202007    8         NaN            264000.0
293212  래미안블레스티지  202007    8         NaN            248000.0
293213  래미안블레스티지  202007    9         NaN            280000.0
293214  래미안블레스티지  202007   12         NaN            200000.0
293215  래미안블레스티지  202007   16         NaN            200000.0
293216  래미안블레스티지  202007   22         NaN            355000.0
293217  래미안블레스티지  202007   30         NaN            265000.0
293218  래미안블레스티지  202008    8         NaN            280000.0
293219  래미안블레스티지  202008    8         NaN            200000.0
293220  래미안블레스티지  202008   11         NaN            315000.0
293221  래미안블레스티지  202009    9         NaN            197000.0
390447  래미안블레스티지  201903   19         NaN            245000.0
390448  래미안블레스티지  201903   23         NaN            230000.0
390449  래미안블레스티지  201904   14         NaN            126000.0
390450  래미안블레스티지  201905   16         NaN            231700.0
390451  래미안블레스티지  201905   17         NaN            204000.0
390452  래미안블레스티지  201905   27         NaN            134000.0
390453  래미안블레스티지  201905   31         NaN            185000.0
390454  래미안블레스티지  201906    1         NaN            160000.0
390455  래미안블레스티지  201906   10         NaN            252000.0
390456  래미안블레스티지  201906   15         NaN            208000.0
390457  래미안블레스티지  201906   15         NaN            197000.0
390458  래미안블레스티지  201906   17         NaN            185000.0
390459  래미안블레스티지  201906   19         NaN            200000.0
390460  래미안블레스티지  201906   19         NaN            205000.0
390461  래미안블레스티지  201906   21         NaN            158000.0
390462  래미안블레스티지  201906   21         NaN            165000.0
390463  래미안블레스티지  201906   25         NaN            149000.0
390464  래미안블레스티지  201906   26         NaN            140000.0
390465  래미안블레스티지  201906   27         NaN            197000.0
390466  래미안블레스티지  201906   28         NaN            220000.0
390467  래미안블레스티지  201907    5         NaN            182000.0
390468  래미안블레스티지  201907   12         NaN            262000.0
390469  래미안블레스티지  201907   12         NaN            230000.0
390470  래미안블레스티지  201907   13         NaN            255000.0
390471  래미안블레스티지  201907   13         NaN            179500.0
390472  래미안블레스티지  201907   14         NaN            184000.0
390473  래미안블레스티지  201907   30         NaN            270000.0
390474  래미안블레스티지  201907   30         NaN            140000.0
390475  래미안블레스티지  201908    2         NaN            235000.0
390476  래미안블레스티지  201908   12         NaN            230000.0
390477  래미안블레스티지  201908   17         NaN            280000.0
390478  래미안블레스티지  201908   20         NaN            185000.0
390479  래미안블레스티지  201908   24         NaN            235000.0
390480  래미안블레스티지  201908   25         NaN            147000.0
390481  래미안블레스티지  201908   26         NaN            254000.0
390482  래미안블레스티지  201908   27         NaN            282000.0
390483  래미안블레스티지  201908   28         NaN            123000.0
390484  래미안블레스티지  201909    7         NaN            300000.0
390485  래미안블레스티지  201909   11         NaN            148000.0
390486  래미안블레스티지  201909   24         NaN            255000.0
390487  래미안블레스티지  201909   27         NaN            232000.0
390488  래미안블레스티지  201909   29         NaN            338000.0

# 해제 사유 발생날짜
해제 사유 발생 여부로 바꿀 수 있을 것 같음.
날짜를 알 수가 없으면 결측치 대신에 0,1 으로 바꾸면 될 것 같음

In [8]:
train["해제사유발생유무"] = np.where(train['해제사유발생일'].notna(),1,0)

In [9]:
correlation = train[['해제사유발생유무', 'target']].corr()
correlation

          해제사유발생유무    target
해제사유발생유무  1.000000  0.066872
target    0.066872  1.000000

# Drop
해제 사유 발생일과 해제사유발생유무, 중개사소재지 Drop

In [10]:
train['is_test'] = 0
test['is_test'] = 1
concat = pd.concat([train, test])

In [11]:
concat.columns

Index(['시군구', '번지', '본번', '부번', '아파트명', '전용면적(㎡)', '계약년월', '계약일', '층', '건축년도',
       '해제사유발생일', '등기신청일자', '거래유형', '중개사소재지', 'k-단지분류(아파트,주상복합등등)',
       'k-세대타입(분양형태)', 'k-복도유형', 'k-난방방식', 'k-전체동수', 'k-전체세대수', 'k-건설사(시공사)',
       'k-사용검사일-사용승인일', 'k-연면적', 'k-주거전용면적', 'k-관리비부과면적', 'k-전용면적별세대현황(60㎡이하)',
       'k-전용면적별세대현황(60㎡~85㎡이하)', 'k-85㎡~135㎡이하', 'k-135㎡초과', 'k-등록일자',
       'k-수정일자', '건축면적', '주차대수', '기타/의무/임대/임의=1/2/3/4', '단지승인일', '사용허가여부',
       '관리비 업로드', '좌표X', '좌표Y', '단지신청일', 'target', '해제사유발생유무', 'is_test'],
      dtype='object')

In [12]:
concat.drop(["해제사유발생유무", "해제사유발생일", "중개사소재지"], axis=1, inplace=True)

In [13]:
concat.head()

,시군구,번지,본번,부번,아파트명,전용면적(㎡),계약년월,계약일,층,건축년도,등기신청일자,거래유형,"k-단지분류(아파트,주상복합등등)",k-세대타입(분양형태),k-복도유형,k-난방방식,k-전체동수,k-전체세대수,k-건설사(시공사),k-사용검사일-사용승인일,k-연면적,k-주거전용면적,k-관리비부과면적,k-전용면적별세대현황(60㎡이하),k-전용면적별세대현황(60㎡~85㎡이하),k-85㎡~135㎡이하,k-135㎡초과,k-등록일자,k-수정일자,건축면적,주차대수,기타/의무/임대/임의=1/2/3/4,단지승인일,사용허가여부,관리비 업로드,좌표X,좌표Y,단지신청일,target,is_test
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201712,8,3,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,124000.0,0
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201712,22,4,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,123500.0,0
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,54.98,201712,28,5,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,91500.0,0
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,3,4,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,130000.0,0
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,8,2,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,117000.0,0

In [14]:
modified_train = concat[concat["is_test"]==0]
modified_test = concat[concat["is_test"]==1]

In [15]:
modified_train.head()
modified_train.drop(["is_test"], axis=1, inplace=True)

In [16]:
modified_test.head()
modified_test.drop(["is_test"], axis=1, inplace=True)

In [17]:
modified_train.head()

,시군구,번지,본번,부번,아파트명,전용면적(㎡),계약년월,계약일,층,건축년도,등기신청일자,거래유형,"k-단지분류(아파트,주상복합등등)",k-세대타입(분양형태),k-복도유형,k-난방방식,k-전체동수,k-전체세대수,k-건설사(시공사),k-사용검사일-사용승인일,k-연면적,k-주거전용면적,k-관리비부과면적,k-전용면적별세대현황(60㎡이하),k-전용면적별세대현황(60㎡~85㎡이하),k-85㎡~135㎡이하,k-135㎡초과,k-등록일자,k-수정일자,건축면적,주차대수,기타/의무/임대/임의=1/2/3/4,단지승인일,사용허가여부,관리비 업로드,좌표X,좌표Y,단지신청일,target
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201712,8,3,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,124000.0
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201712,22,4,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,123500.0
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,54.98,201712,28,5,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,91500.0
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,3,4,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,130000.0
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성,79.97,201801,8,2,1987,,-,아파트,분양,계단식,개별난방,8.0,270.0,우성건설,1987-11-21 00:00:00.0,22637.0,20204.0,22637.0,20.0,250.0,0.0,NaN,2022-11-09 20:10:43.0,2023-09-23 17:21:41.0,4858.0,262.0,임의,2022-11-17 13:00:29.0,Y,N,127.05721,37.476763,2022-11-17 10:19:06.0,117000.0

In [18]:
modified_test.to_csv("../modified_data/v02_test.csv")
modified_train.to_csv("../modified_data/v02_train.csv")